#!/bin/bash
#
# Pre-build script for PU850 ESP8266 firmware
# Bash equivalent of .vscode/prebuild.cmd for Linux/CI environments
#
# This script is called by build.sh before compilation
#

cd "${VSCA_WORKSPACE_DIR:-.}"

# define variables
h_file="~local.h"

# put the contents of the hostname command into a variable
HOSTNAME_VAR=$(hostname 2>/dev/null || echo "unknown")
USERNAME_VAR=$(whoami 2>/dev/null || echo "ci")
DATE_VAR=$(date "+%m/%d/%Y")
TIME_VAR=$(date "+%H:%M:%S")

# delete file if exists
rm -f "$h_file" 2>/dev/null

# create new file with header
cat > "$h_file" << EOF
#pragma once

/**
 * This file was auto-generated by $(basename "${BASH_SOURCE[0]}"). Do not modify it manually.
 *
 * Generated on ${DATE_VAR} ${TIME_VAR} by ${USERNAME_VAR} on ${HOSTNAME_VAR}
 *
 */

#define SKETCH_NAME "${VSCA_SKETCH:-ASA0002E.ino}"
#define BUILD_USERNAME "${USERNAME_VAR}"
#define BUILD_HOSTNAME "${HOSTNAME_VAR}"
EOF

# Note: On Windows, prebuild.cmd uses 'attrib +h' to hide the file.
# On Linux/macOS, files starting with ~ are conventionally treated as temporary/hidden.
# No equivalent action needed as ~ prefix serves a similar purpose in Unix-like systems.

# clean up old checksum file
rm -f "${VSCA_BUILD_DIR:-./Build}/${VSCA_SKETCH:-ASA0002E.ino}.bin.md5" 2>/dev/null

# clean up old h file in build directory
rm -f "${VSCA_BUILD_DIR:-./Build}/sketch/${h_file}" 2>/dev/null

exit 0
