@echo off
cd /d "%VSCA_WORKSPACE_DIR%"

setlocal enableextensions enabledelayedexpansion

:: define variables
set h_file=~local.h

:: Check if we're in CI environment (GitHub Actions sets CI=true)
if defined CI (
    :: In CI: use git commit info instead of hostname/username
    for /f "tokens=*" %%a in ('git rev-parse --short HEAD 2^>nul') do set GIT_COMMIT_HASH=%%a
    for /f "tokens=*" %%a in ('git log -1 --format^=%%cd --date^=format:"%%Y-%%m-%%d %%H:%%M:%%S" 2^>nul') do set GIT_COMMIT_DATE=%%a
    for /f "tokens=*" %%a in ('git log -1 --format^=%%cn 2^>nul') do set GIT_COMMITTER_NAME=%%a
    for /f "tokens=*" %%a in ('git log -1 --format^=%%ce 2^>nul') do set GIT_COMMITTER_EMAIL=%%a
    
    if not defined GIT_COMMIT_HASH set GIT_COMMIT_HASH=unknown
    if not defined GIT_COMMITTER_NAME set GIT_COMMITTER_NAME=CI
    if not defined GIT_COMMITTER_EMAIL set GIT_COMMITTER_EMAIL=ci@build
    if not defined GIT_COMMIT_DATE set GIT_COMMIT_DATE=unknown
    
    set BUILD_BY=!GIT_COMMITTER_NAME! ^<!GIT_COMMITTER_EMAIL!^>
    set BUILD_ON=commit !GIT_COMMIT_HASH! (!GIT_COMMIT_DATE!)
) else (
    :: Local build: use hostname/username
    for /f "tokens=*" %%a in ('hostname') do set HOSTNAME=%%a
    set BUILD_BY=%USERNAME%
    set BUILD_ON=!HOSTNAME!
)

:: delete file if exists
if exist "%h_file%" del "%h_file%" /f /q /a >nul 2>&1

:: create new file
echo #pragma once> "%h_file%"
echo.>> "%h_file%"

:: add auto-generated warning
echo /**>> "%h_file%"
echo  * This file was auto-generated by %~nx0. Do not modify it manually.>> "%h_file%"
echo  *>> "%h_file%"
echo  * Generated on %DATE% %TIME% by !BUILD_BY! on !BUILD_ON!>> "%h_file%"
echo  *>> "%h_file%"
echo  */>> "%h_file%"
echo.>> "%h_file%"

:: make the file hidden
attrib +h "%h_file%"

:: add sketch definations
echo #define SKETCH_NAME "%VSCA_SKETCH%">> "%h_file%"

:: add user definations
echo #define BUILD_USERNAME "!BUILD_BY!">> "%h_file%"
echo #define BUILD_HOSTNAME "!BUILD_ON!">> "%h_file%"

:: clean up old checksum file
if exist "%VSCA_BUILD_DIR%\%VSCA_SKETCH%.bin.md5" del "%VSCA_BUILD_DIR%\%VSCA_SKETCH%.bin.md5" /f /q /a >nul 2>&1

:: clean up old h file
if exist "%VSCA_BUILD_DIR%\sketch\%h_file%" del "%VSCA_BUILD_DIR%\sketch\%h_file%" /f /q /a >nul 2>&1

:: change the h file's timestamp to the main file
:: touch -c --reference="%VSCA_BUILD_DIR%\%VSCA_SKETCH%.bin" "%h_file%"
