@echo off
cd /d "%VSCA_WORKSPACE_DIR%"

setlocal enableextensions enabledelayedexpansion

:: define variables
set h_file=~local.h

:: put the contents of the hostname command into a variable
for /f "tokens=*" %%a in ('hostname') do set HOSTNAME=%%a

:: delete file if exists
if exist "%h_file%" del "%h_file%" /f /q /a >nul 2>&1

:: create new file
echo #pragma once> "%h_file%"
echo.>> "%h_file%"

:: add auto-generated warning
echo /**>> "%h_file%"
echo  * This file was auto-generated by %~nx0. Do not modify it manually.>> "%h_file%"
echo  *>> "%h_file%"
echo  * Generated on %DATE% %TIME% by %USERNAME% on %HOSTNAME%>> "%h_file%"
echo  *>> "%h_file%"
echo  */>> "%h_file%"
echo.>> "%h_file%"

:: make the file hidden
attrib +h "%h_file%"

:: add sketch definations
echo #define SKETCH_NAME "%VSCA_SKETCH%">> "%h_file%"

:: add user definations
echo #define BUILD_USERNAME "%USERNAME%">> "%h_file%"
echo #define BUILD_HOSTNAME "%HOSTNAME%">> "%h_file%"

:: clean up old checksum file
if exist "%VSCA_BUILD_DIR%\%VSCA_SKETCH%.bin.md5" del "%VSCA_BUILD_DIR%\%VSCA_SKETCH%.bin.md5" /f /q /a >nul 2>&1

:: clean up old h file
if exist "%VSCA_BUILD_DIR%\sketch\%h_file%" del "%VSCA_BUILD_DIR%\sketch\%h_file%" /f /q /a >nul 2>&1

:: change the h file's timestamp to the main file
:: touch -c --reference="%VSCA_BUILD_DIR%\%VSCA_SKETCH%.bin" "%h_file%"
