#!/bin/bash
#
# Pre-build script for PU850 ESP8266 firmware
# Bash equivalent of .vscode/prebuild.cmd for Linux/CI environments
#
# This script is called by build.sh before compilation
#

cd "${VSCA_WORKSPACE_DIR:-.}"

# define variables
h_file="~local.h"

DATE_VAR=$(date "+%m/%d/%Y")
TIME_VAR=$(date "+%H:%M:%S")

# Check if we're in CI environment
if [[ -n "${CI:-}" || -n "${GITHUB_ACTIONS:-}" || -n "${RUNNER_OS:-}" ]]; then
    # In CI: use git commit info instead of hostname/username
    GIT_COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
    GIT_COMMIT_DATE=$(git log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S' 2>/dev/null || echo "unknown")
    GIT_COMMITTER_NAME=$(git log -1 --format=%cn 2>/dev/null || echo "CI")
    GIT_COMMITTER_EMAIL=$(git log -1 --format=%ce 2>/dev/null || echo "ci@build")
    
    # Use git info for build metadata
    BUILD_BY="${GIT_COMMITTER_NAME} <${GIT_COMMITTER_EMAIL}>"
    BUILD_ON="commit ${GIT_COMMIT_HASH} (${GIT_COMMIT_DATE})"
else
    # Local build: use hostname/username
    HOSTNAME_VAR=$(hostname 2>/dev/null || echo "unknown")
    USERNAME_VAR=$(whoami 2>/dev/null || echo "ci")
    
    BUILD_BY="${USERNAME_VAR}"
    BUILD_ON="${HOSTNAME_VAR}"
fi

# delete file if exists
rm -f "$h_file" 2>/dev/null

# create new file with header
cat > "$h_file" << EOF
#pragma once

/**
 * This file was auto-generated by $(basename "${BASH_SOURCE[0]}"). Do not modify it manually.
 *
 * Generated on ${DATE_VAR} ${TIME_VAR} by ${BUILD_BY} on ${BUILD_ON}
 *
 */

#define SKETCH_NAME "${VSCA_SKETCH:-ASA0002E.ino}"
#define BUILD_USERNAME "${BUILD_BY}"
#define BUILD_HOSTNAME "${BUILD_ON}"
EOF

# Note: On Windows, prebuild.cmd uses 'attrib +h' to hide the file.
# On Linux/macOS, files starting with ~ are conventionally treated as temporary/hidden.
# No equivalent action needed as ~ prefix serves a similar purpose in Unix-like systems.

# clean up old checksum file
rm -f "${VSCA_BUILD_DIR:-./Build}/${VSCA_SKETCH:-ASA0002E.ino}.bin.md5" 2>/dev/null

# clean up old h file in build directory
rm -f "${VSCA_BUILD_DIR:-./Build}/sketch/${h_file}" 2>/dev/null

exit 0
